START TRANSACTION;

CREATE TABLE "Permissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "ResourceUri" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "Type" integer NOT NULL,
    CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Description" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(50) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Email" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastLogin" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "RolePermissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "PermissionId" integer NOT NULL,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RolePermissions_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

INSERT INTO "Permissions" ("Id", "Description", "Name", "ResourceUri", "Type")
VALUES (1, '访问系统首页', '首页访问', '/', 0);
INSERT INTO "Permissions" ("Id", "Description", "Name", "ResourceUri", "Type")
VALUES (2, '管理系统用户', '用户管理', '/users', 0);
INSERT INTO "Permissions" ("Id", "Description", "Name", "ResourceUri", "Type")
VALUES (3, '管理系统角色', '角色管理', '/admin/roles', 0);
INSERT INTO "Permissions" ("Id", "Description", "Name", "ResourceUri", "Type")
VALUES (4, '管理系统权限', '权限管理', '/permissions', 0);

INSERT INTO "Roles" ("Id", "Description", "Name")
VALUES (1, '系统管理员，拥有所有权限', '管理员');
INSERT INTO "Roles" ("Id", "Description", "Name")
VALUES (2, '普通用户，拥有基本权限', '普通用户');

INSERT INTO "RolePermissions" ("Id", "PermissionId", "RoleId")
VALUES (1, 1, 1);
INSERT INTO "RolePermissions" ("Id", "PermissionId", "RoleId")
VALUES (2, 2, 1);
INSERT INTO "RolePermissions" ("Id", "PermissionId", "RoleId")
VALUES (3, 3, 1);
INSERT INTO "RolePermissions" ("Id", "PermissionId", "RoleId")
VALUES (4, 4, 1);
INSERT INTO "RolePermissions" ("Id", "PermissionId", "RoleId")
VALUES (5, 3, 1);

CREATE INDEX "IX_RolePermissions_PermissionId" ON "RolePermissions" ("PermissionId");

CREATE INDEX "IX_RolePermissions_RoleId" ON "RolePermissions" ("RoleId");

CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");

CREATE INDEX "IX_UserRoles_UserId" ON "UserRoles" ("UserId");


COMMIT;

